### ISSUE TITLE
xl console hangs

### ISSUE THREAD

**Issue by lchan12** [GaloisInc/FreeRTOS-Xen#3]
hi, I have a problem after "xl console [my-domain-name]". It just hangs... Nothing happens and I can't type anything. A console for DomU(FreeRTOS) doesn't appear.

I followed 'Step 1' & 'Step 2' well. And I built "Example" application in Step 2.

It works well until I type the command "xl create -f .../path/to/domain.cfg".

Then I found DomU working by "xl list" command.

```
root@Dom0:~# xl list
Name                                        ID   Mem VCPUs      State   Time(s)
Domain-0                                     0   128     2     r-----      40.2
Example                                      1    32     1     r-----       2.8
```

when I type "xl console Example", 

```
root@Dom0:~# xl list
Name                                        ID   Mem VCPUs      State   Time(s)
Domain-0                                     0   128     2     r-----      40.2
Example                                      1    32     1     r-----       2.8
root@Dom0:~# xl console Example
(The cursor is blinking here.)
```

The "xl console" command is not supported?

**Comment by jtdaugherty** [comment]
The console is supported only in read-only mode, so you will not be able to give any input to the FreeRTOS domain.  However, if you are not getting any output at all, then it's possible the domain is failing to boot in some way.  To get more information, you'll need to rebuild Xen with debugging output enabled from guest domains.  For more information and some things to try, please see https://github.com/GaloisInc/FreeRTOS-Xen/issues/1.

**Comment by lchan12** [comment]
Thanks @jtdaugherty  . I saw #1 , however, the same issue occurred.

So I was trying many different solutions, and I finally found this command from Xen Wiki.

```
root@Dom0:~# xl -vvv create -d [myDom.cfg]
```

This command show some debug messages. I watched this message with "ERIKA Enterprise(DomU)".

Because I have a new problem with FreeRTOS. I don't know why this new issue happen.

```
root@Dom0:~# xl list
Name                                        ID   Mem VCPUs      State   Time(s)
Domain-0                                     0   128     2     r-----     102.1
root@Dom0:~# xl create DomU_rtos.cfg 
Parsing config from DomU_rtos.cfg
xc: error: panic: xc_dom_core.c:225: tried to map file which is too large: Out of memory
libxl: error: libxl_dom.c:546:libxl__build_pv: xc_dom_kernel_file failed: No such file or directory
libxl: error: libxl_create.c:1121:domcreate_rebuild_done: cannot (re-)build domain: -3
root@Dom0:~# 
```

I forgot the size of "Example.bin" before this error occurred. But now, the size of "Example.bin" is about 2.1GB.
```
root@Dom0:~# ll
total 2100392
drwx------  3 root root       4096 Nov  5 02:43 ./
drwxr-xr-x 21 root root       4096 Aug 31 06:16 ../
-rw-r--r--  1 root root       3106 Feb 20  2014 .bashrc
drwx------  2 root root       4096 Nov  5 02:34 .cache/
-rw-r--r--  1 root root        140 Feb 20  2014 .profile
-rw-r--r--  1 root root        131 Nov  5 02:43 DomU_rtos.cfg
-rw-r--r--  1 root root 2148663576 Nov  5 02:05 Example.bin
```
Althought I turned off the "DEBUG" options from "example", "demo" source codes that I saw #1 , the size of Example.bin was same.

Is the size of "Example.bin" right? If not, why my Example.bin has been fat? :<

**Comment by jtdaugherty** [comment]
The `Example.bin` file will only be that big if the `configTOTAL_HEAP_SIZE` constant in `CORTEX_A15_Xen_GCC/include/FreeRTOSConfig.h` has been set to a very large number (probably 2 GB in this case).  You will only be able to load that kernel image if your `DomU_rtos.cfg` file also specifies at least that much memory for the guest Xen domain.  So your options are:
* Increase the `memory` setting in your guest domain config, or
* Reduce the value of `configTOTAL_HEAP_SIZE` to a number that will result in a kernel image that can fit into the configured heap size.

**Comment by ligang23090** [comment]
Hi, @jtdaugherty, I am using this Freertos port. my problem is exactly the same as lchan12. The size of my Example.bin is also 2.1G. after i reduce the value of configTOTAL_HEAP_SIZE. It is still 2.1G. I am new to freertos and xen. can you help me? Thank you very much

**Comment by jtdaugherty** [comment]
@ligang23090 - do you have a repository with the relevant configuration and source files that I can check out and inspect?

**Comment by UnePierre** [comment]
I had the same 2GiB problem and solved it by preventing some "id" symbols from getting linked in my `Example/Makefile`
```diff
-- LDFLAGS=-nostartfiles -Xlinker
++ LDFLAGS=-nostartfiles -Xlinker --build-id=none
```
However, the issue of not getting any console output remains.

BTW, I'm compiling natively in Dom0 on a CubieTruck with MirageOS.  Mirage-DomU-examples work with console output, which is going to CubieTruck's serial.

**Comment by UnePierre** [comment]
@jtdaugherty - I've built my platform on the CubieTruck using [MirageOS' Xen-ARM-Builder](https://github.com/mirage/xen-arm-builder):
* Xen4.4 (with  debug=y)
* Ubuntu Trusty armhf @ Dom0
* [Mirage Skeleton Examples](https://github.com/mirage/mirage-skeleton) work and have console output to `dtuart`; also network is up-and-running, e.g. [static_website](https://github.com/mirage/mirage-skeleton/tree/master/static_website) (1)
* [FreeRTOS-Xen/Example ](https://github.com/GaloisInc/FreeRTOS-Xen/tree/master/Example) compiles, links and runs (endlessly), but gives no console output, not even for startup.
* Same with [FreeRTOS_8_2_0](https://github.com/GaloisInc/FreeRTOS-Xen/tree/FreeRTOS_8_2_0) branch.

As with #1, I'm guessing it might be somewhere at the system initialization, rather than the hypervisor call level.

(1) Example console output from mirage-skeleton/static_website:
```text
(d63) Virtual -> physical offset = 7fc00000
(d63) Checking DTB at 08400000...
(d63) Xen Minimal OS!
(d63) Initialising console ... done.
(XEN) grant_table.c:1266:d63 Expanding dom (63) grant table from (1) to (2) frames.
(XEN) grant_table.c:1266:d63 Expanding dom (63) grant table from (2) to (3) frames.
(XEN) grant_table.c:1266:d63 Expanding dom (63) grant table from (3) to (4) frames.
(d63) getenv(OCAMLRUNPARAM) -> null
(d63) getenv(CAMLRUNPARAM) -> null
(d63) getenv(PATH) -> null
(d63) Unsupported function lseek called in Mini-OS kernel
(d63) Unsupported function lseek called in Mini-OS kernel
(d63) Unsupported function lseek called in Mini-OS kernel
(d63) getenv(OCAMLRUNPARAM) -> null
(d63) getenv(CAMLRUNPARAM) -> null
(d63) getenv(TMPDIR) -> null
(d63) getenv(TEMP) -> null
(d63) Attempt to open(/dev/urandom)!
(d63) Unsupported function getpid called in Mini-OS kernel
(d63) Unsupported function getppid called in Mini-OS kernel
```
nothing more on `xl destroy www`.

**Comment by jtdaugherty** [comment]
Thanks for those details, @UnePierre and others.  Unfortunately I don't think I can help much if the domain isn't producing any output at all, since that kind of behavior could be caused by a long list of possible problems, some of which might be related to the fact that you're running Xen 4.4 (since I developed this on 4.4 before it was released and a lot probably changed once it was officially out).

Some basics may need to be checked on, such as whether the emergency debug console hypercall is using the correct parameters (again, assuming something important changed in the 4.4 release).  Using that hypercall doesn't depend on setting up any Xen services so it can be used extremely early in the domU boot process to e.g. dump registers.  You'll need to resort to these kinds of tactics since I don't have enough visibility into what could be going wrong and there could be many causes.  I'm sorry I can't be more helpful!  (But thanks to you all for continuing to post updates here about what you've tried.)

**Comment by UnePierre** [comment]
Using a more recent version of the xen-arm-builder [1]:
* Xen4.5
* Ubuntu 15.04 vidvid in Dom0
* Branch "FreeRTOS_8_2_0"
gives no console output either.

Maybe helpful for further ideas:
* The FreeRTOS-DomU races to 100% CPU usage within 2 seconds and stays there indefinitely -- despite the following example implementation:
```C99
#include <FreeRTOS.h>

int main(void)
{
   return 0;
}
```

Adding some ```printk()``` doesn't change the behavior.

**Comment by jtdaugherty** [comment]
@UnePierre - using a  newer version of Xen increases the chance of arcane problems since much may have changed in the ARM virtualization code (thus breaking assumptions I made in FreeRTOS setup).  You mentioned that the CPU usage goes to 100%; that's probably because of a CPU exception.  When a CPU exception is handled, the last thing the code does (see `vectors.s`) is go into an infinite loop branching in-place since the exception is unrecoverable.

**Comment by jtdaugherty** [comment]
In particular,

https://github.com/GaloisInc/FreeRTOS-Xen/blob/master/Source/portable/GCC/ARM7_CA15_Xen/asm/vectors.s#L80

**Comment by dumpram** [comment]
Last few lines of output:
<code> 
libxl: debug: libxl_event.c:2193:libxl__ao_progress_report: ao 0x3c1d0: progress report: callback queued aop=0x388c8

libxl: debug: libxl_event.c:1874:libxl__ao_complete: ao 0x3c1d0: complete, rc=0

libxl: debug: libxl_event.c:1410:egc_run_callbacks: ao 0x3c1d0: progress report: callback aop=0x388c8

libxl: debug: libxl_create.c:1580:do_domain_create: ao 0x3c1d0: inprogress: poller=0x3c230, flags=ic

libxl: debug: libxl_event.c:1843:libxl__ao__destroy: ao 0x3c1d0: destroy
</code>
Last function is the same as when booting Linux uDom but i get no output? I think there's problem in boot.s which causes SWI or something and it newer reaches print_banner. But I don't know why or how to debug it. Can I somehow print from dummy interrupt handlers in vectors.s. Thank you in advance...

**Comment by jtdaugherty** [comment]
In case anyone involved in this ticket is still engaged, I've been doing some work on this project this week and some recent commits should improve matters.  I still have more work I want to do, but I've been able to get this working again on Xen 4.7 on an Arndale board.

**Comment by jtdaugherty** [comment]
Due to the recent work I've completed to get this working on Xen 4.7, I'm going to close this due to inactivity. Feel free to re-open new issues if any problems persist. Thanks!
